version: '3'
services:
  eventbus:
    build: eventbus
    restart: unless-stopped
    ports:
    - "8080:8080"
    environment:
      REDIS_URL: "redis://redis:6379/1"
    depends_on:
    - redis
  djangoserver:
    build: django-server
    restart: unless-stopped
    ports:
    - "8000:8000"
    command: 'make run_dev'
    volumes:
    - ./django-server:/app
    environment:
      DATABASE_URL: "postgres://admin:admin@postgres:5432/db"
      CACHE_URL: "redis://redis:6379/1"
    depends_on:
    - redis
    - postgres
  stravapolling:
    build: stravapolling
    volumes:
    - ./stravapolling:/app
    environment:
      DJANGO_SERVER_HOST_API_URL: "http://djangoserver:8000"
    env_file:
      - secrets.env
    depends_on:
    - djangoserver
  randomphoto:
    build: randomphoto
    restart: unless-stopped
    environment:
      NEW_PHOTO_INTERVAL: 300
      RANDOM_PHOTO_MODE: "SAME_DAY_ANOTHER_YEAR"
      DJANGO_SERVER_HOST_API_URL: "http://djangoserver:8000"
    env_file:
      - secrets.env
    depends_on:
    - djangoserver
  redis:
    image: redis
    restart: unless-stopped
  postgres:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
    - db-data:/var/lib/postgresql/data
  mqtthandler-server:
    build: mqtthandler-server
    restart: unless-stopped
    volumes:
    - mqtthandler-server-data:/data
  frontend:
    build: frontend
    restart: unless-stopped
    ports:
    - "80:80"
    command: 'make run'
  mqtt-mosquitto:
    image: eclipse-mosquitto
    volumes:
    - mqtt-data:/mosquitto/data
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    volumes:
      - zigbee-gateway-data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
  
volumes:
  db-data:
  zigbee-gateway-data:
  mqtt-data:
  mqtthandler-server-data:
