# Generated by Django 2.2.7 on 2019-11-20 12:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("payload", django.contrib.postgres.fields.jsonb.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
