# Generated by Django 2.2.7 on 2019-11-20 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("eventstream", "0002_activity")]

    operations = [
        migrations.DeleteModel(name="Activity"),
        migrations.AlterField(
            model_name="event",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
