# Generated by Django 3.0 on 2020-01-25 22:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("eventstream", "0004_auto_20191207_2151")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="frontend_payload",
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="payload",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
