# Generated by Django 3.1.3 on 2020-11-13 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("eventstream", "0005_auto_20200125_2211")]

    operations = [
        migrations.RemoveField(model_name="event", name="frontend_payload"),
        migrations.AlterField(
            model_name="event", name="event_type", field=models.CharField(max_length=64)
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
