# Generated by Django 3.0 on 2020-01-25 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("actions", "0002_appperson")]

    operations = [
        migrations.CreateModel(
            name="StravaAthlete",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("athlete_id", models.CharField(max_length=255, unique=True)),
                ("scope", models.CharField(max_length=255)),
                ("access_token", models.CharField(max_length=255)),
                ("refresh_token", models.CharField(max_length=255)),
                ("expires_at", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="StravaActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_id", models.CharField(max_length=255, unique=True)),
                ("start_date", models.DateTimeField()),
                (
                    "strava_athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="actions.StravaAthlete",
                    ),
                ),
            ],
        ),
    ]
